### ISSUE TITLE
It seems that the given email address does not exist

### ISSUE THREAD

**Issue by IncludeMathH** [weijiawu/BOVText-Benchmark#2]
When I tried to send a confirmation email to you, the mail system showed that the address does not exist. If possible, I would like to have a valid email address.

**Comment by IncludeMathH** [comment]
I believe we are both alumni, members of Zhejiang University, so a Zhejiang University email address would be fine.

**Comment by weijiawu** [comment]
please using   weijiawu96@gmail.com

**Comment by IncludeMathH** [comment]
> please using [weijiawu96@gmail.com](mailto:weijiawu96@gmail.com)

Thanks.
